### ISSUE TITLE
revert 'exports' in question bank

### ISSUE THREAD

**Issue by pacree** [mmansfield/edCorrelatorY#4]
Unless these need to be in their own thing for the "security/user permissions" ... Can you revert to the old way, where both were just displayed on the the bar across the top? 
It's more clicks in the new way... I wear out mice fast enough as it is! 

![image](https://cloud.githubusercontent.com/assets/4050932/7525395/105b0dac-f4d7-11e4-9bc3-f28736b6fd5e.png)

**Comment by mmansfield** [comment]
Its a usability issue.  Because the number of reports and exports will grow
it makes sense to group them.  There us not enough room on the primary nav
for users who have access to all features.  Reporting is also not a heavily
used feature so one extra click should not be an issue.

**Comment by pacree** [comment]
ahh, ok.  didn't realize there were more things that i couldn't see on there.
